baseURL: https://costinstefan.ro
disablePathToLower: true
enableEmoji: true
languageCode: en-us
title: Costin Stefan
theme: "PaperMod"
paginate: 5
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
services:
  googleAnalytics:
    ID: G-LSWRL8FMXN 
copyright: "The opinions expressed here are entirely mine. You can copy freely everything you see here, but I shall not be held liable in case of any damages to production systems."
googleAnalytics: 354181620 
ShowFullTextinRSS: true
minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Costin Stefan
  description: "Costin Stefan is a Technical Consultant with a vast experience in Networking, Security, Virtualization, Kubernetes and DevOps"
  keywords: [Blog, Costin Stefan, DevOps, networking, Cisco, Kubernetes, Cilium, Ansible, Prometheus, Grafana, deployment pipelines, CICD, Openshift, vmware, vsphere, vcenter, costin, stefan, security, servers]
  author: costin 
  images: ["https://costinstefan.ro/images/me.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/icons/favicon-16x16.png"
    favicon32x32: "/icons/favicon-32x32.png"
    apple_touch_icon: "/icons/apple-touch-icon.png"
    safari_pinned_tab: "/icons/apple-touch-icon.png"

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Costin Stefan
    subtitle: "Technical Consultant"
    imageUrl: "https://costinstefan.ro/images/me.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: 
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Costin Stefan"
    Content: Welcome to my blog. You will find useful random stuff, mostly IT infra-related.

  socialIcons:
# OFF ON 14012025
#    - name: linkedin
#      url: "https://linkedin.com/in/costinstefan"

  analytics:
    google:
      SiteVerificationTag: ""
    bing:
      SiteVerificationTag: "354181620"

  cover:
    responsiveImages: false
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/caustee/hugo/tree/main/content/"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about-me
      name: About me
      url: /me/
      weight: 10
    - identifier: hello
      name: Say Hello
      url: /contact/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 35

    # Grouped under "How can I help you?"
    - identifier: help
      name: How can I help you?
      url: ""
      weight: 40

    - identifier: consultancy
      name: Consultancy
      url: /help/consultancy/
      parent: help
      weight: 41

    - identifier: project-implementation
      name: Project Implementation
      url: /help/project-implementation/
      parent: help
      weight: 42

    - identifier: recruiting-screening
      name: Recruiting Screening
      url: /help/recruiting-screening/
      parent: help
      weight: 43

    - identifier: automated-deployments
      name: Automated Deployments
      url: /help/automated-deployments/
      parent: help
      weight: 44

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

